from .cls_head import ClsHead
from .contrastive_head import ContrastiveHead
from .contrastive_odc_head import ContrastiveODCHead
from .contrastive_odc_head_v7 import ContrastiveODCHead_V7
from .contrastive_odc_head_v12 import ContrastiveODCHead_V12
from .contrastive_odc_head_v24 import ContrastiveODCHead_V24
from .latent_pred_head import LatentPredictHead
from .multi_cls_head import MultiClsHead
